import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { docsLoader } from "@astrojs/starlight/loaders";
import type { Loader, LoaderContext } from "astro/loaders";

/** GitHub location of the monorepo — relative README links that don't map to a site page land here. */
export const REPO_URL = "https://github.com/MantleJs/mantle";
const BRANCH = "main";

/** One README ingested as a docs page. `repoPath` is the README's directory relative to the repo root. */
interface ReadmeSource {
  id: string;
  repoPath: string;
}

/**
 * Starlight's `docsLoader()` for the authored pages in `src/content/docs/`, plus every package README
 * (`packages/<name>/README.md` → `/packages/<name>/`) and the UI registry README (`registry/README.md`
 * → `/blocks/`), read at build time. The READMEs stay the single source of truth: nothing is copied
 * into the site, and an edit to a README changes the next build.
 */
export function docsWithReadmes(): Loader {
  const docs = docsLoader();
  return {
    name: "mantle-docs-with-readmes",
    async load(context) {
      // Runs first: the glob loader prunes store entries it didn't produce, which also clears README
      // entries left over from a previous (cached) build before they're re-added below.
      await docs.load(context);
      const repoRoot = fileURLToPath(new URL("../", context.config.root));
      const sources = await readmeSources(repoRoot);
      const packageNames = new Set(sources.filter((s) => s.id.startsWith("packages/")).map((s) => s.id.slice(9)));
      for (const source of sources) {
        await loadReadme(context, repoRoot, source, packageNames);
      }
      // `astro dev`: re-ingest a README when it's edited.
      context.watcher?.on("change", (changed) => {
        const source = sources.find((s) => path.join(repoRoot, s.repoPath, "README.md") === changed);
        if (source) void loadReadme(context, repoRoot, source, packageNames);
      });
    },
  };
}

async function readmeSources(repoRoot: string): Promise<ReadmeSource[]> {
  const packagesDir = path.join(repoRoot, "packages");
  const names = (await readdir(packagesDir, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const sources: ReadmeSource[] = [];
  for (const name of names) {
    const exists = await readFile(path.join(packagesDir, name, "README.md"), "utf8").then(
      () => true,
      () => false,
    );
    if (exists) sources.push({ id: `packages/${name}`, repoPath: `packages/${name}` });
  }
  sources.push({ id: "blocks", repoPath: "registry" });
  return sources;
}

async function loadReadme(
  context: LoaderContext,
  repoRoot: string,
  source: ReadmeSource,
  packageNames: Set<string>,
): Promise<void> {
  const readmePath = path.join(repoRoot, source.repoPath, "README.md");
  const raw = await readFile(readmePath, "utf8");
  const { title, description, body } = splitReadme(raw, source.repoPath);
  const markdown = rewriteLinks(body, source.repoPath, packageNames);
  const data = await context.parseData({
    id: source.id,
    data: {
      title,
      description,
      editUrl: `${REPO_URL}/edit/${BRANCH}/${source.repoPath}/README.md`,
    },
  });
  // The path a hand-written page with this id would have had. Starlight places autogenerated sidebar
  // entries by their path inside the docs collection, and starlight-links-validator registers a page
  // (and its heading anchors) under the file it was rendered from — so the README claims this path.
  const virtualPath = `src/content/docs/${source.id}.md`;
  context.store.set({
    id: source.id,
    data,
    body: markdown,
    rendered: await context.renderMarkdown(markdown, { fileURL: new URL(virtualPath, context.config.root) }),
    digest: context.generateDigest(markdown + title),
    filePath: virtualPath,
  });
  context.watcher?.add(readmePath);
}

/** First `# Heading` becomes the page title (Starlight renders it); the first prose paragraph, the description. */
export function splitReadme(raw: string, repoPath: string): { title: string; description?: string; body: string } {
  const lines = raw.replace(/\r\n/g, "\n").split("\n");
  const headingIndex = lines.findIndex((line) => /^# \S/.test(line));
  const title = headingIndex >= 0 ? lines[headingIndex].slice(2).trim() : path.basename(repoPath);
  const bodyLines = headingIndex >= 0 ? lines.slice(headingIndex + 1) : lines;
  const paragraph: string[] = [];
  for (const line of bodyLines) {
    if (line.trim() === "") {
      if (paragraph.length > 0) break;
      continue;
    }
    if (/^(#|```|~~~|\||>|---|- |\* |<)/.test(line.trim())) {
      if (paragraph.length > 0) break;
      continue;
    }
    paragraph.push(line.trim());
  }
  const description = paragraph.length > 0 ? toPlainText(paragraph.join(" ")) : undefined;
  return { title: title.replace(/`/g, ""), description, body: bodyLines.join("\n") };
}

function toPlainText(markdown: string): string {
  return markdown
    .replace(/!?\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/[`*_]/g, "")
    .trim();
}

/**
 * Rewrite relative links for the page's new home: another package's README → its `/packages/…/` page,
 * the registry README → `/blocks/`, anything else in the repo → GitHub. Code fences and inline code
 * are left alone (`handlers[i](event)` is code, not a link).
 */
export function rewriteLinks(markdown: string, repoPath: string, packageNames: Set<string>): string {
  let fence: string | undefined;
  return markdown
    .split("\n")
    .map((line) => {
      const marker = /^\s*(```|~~~)/.exec(line)?.[1];
      if (marker) {
        if (fence === undefined) fence = marker;
        else if (marker === fence) fence = undefined;
        return line;
      }
      if (fence !== undefined) return line;
      return line
        .split(/(`+[^`]*`+)/)
        .map((segment, index) => (index % 2 === 1 ? segment : rewriteSegment(segment, repoPath, packageNames)))
        .join("");
    })
    .join("\n");
}

function rewriteSegment(segment: string, repoPath: string, packageNames: Set<string>): string {
  return segment.replace(
    /(!?)\]\((<?)([^)\s>]+)(>?)((?:\s+"[^"]*")?)\)/g,
    (_match, bang: string, open: string, target: string, close: string, titlePart: string) =>
      `${bang}](${open}${resolveTarget(target, repoPath, packageNames, bang === "!")}${close}${titlePart})`,
  );
}

function resolveTarget(target: string, repoPath: string, packageNames: Set<string>, isImage: boolean): string {
  if (/^[a-z][a-z0-9+.-]*:/i.test(target) || target.startsWith("#") || target.startsWith("/")) return target;
  const hashIndex = target.indexOf("#");
  const pathPart = hashIndex >= 0 ? target.slice(0, hashIndex) : target;
  const hash = hashIndex >= 0 ? target.slice(hashIndex) : "";
  const resolved = path.posix.normalize(path.posix.join(repoPath, pathPart)).replace(/\/+$/, "");
  const page = /^packages\/([^/]+)(?:\/README\.md)?$/.exec(resolved);
  if (page && packageNames.has(page[1])) return `/packages/${page[1]}/${hash}`;
  if (resolved === "registry" || resolved === "registry/README.md") return `/blocks/${hash}`;
  if (resolved === `${repoPath}/README.md` || resolved === repoPath) return hash || "#";
  if (isImage) return `https://raw.githubusercontent.com/MantleJs/mantle/${BRANCH}/${resolved}`;
  return `${REPO_URL}/blob/${BRANCH}/${resolved}${hash}`;
}
